language: node_js

node_js:
  - '4.3'

sudo: required

group: edge

services:
  - docker

env:
  - NODE_VERSION_X=010
  - NODE_VERSION_X=012
  - NODE_VERSION_X=4
  - NODE_VERSION_X=5

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - ./tools/test_all.sh

deploy:
  provider: script
  script: ./tools/push.sh
  on:
    tags: true