language: node_js
sudo: required
services:
  - docker

matrix:
  include:
    - node_js: "6.11"
      env: NODE_VERSION_X=6
      services:
        - docker
    - node_js: "6.11"
      env: NODE_VERSION_X=alpine_6
      services:
        - docker
    - node_js: "8.8"
      env: NODE_VERSION_X=8
      services:
        - docker
    - node_js: "8.8"
      env: NODE_VERSION_X=alpine_8
      services:
        - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - ./tools/pre_push.sh

deploy:
  provider: script
  script: ./tools/push.sh
  on:
    repo: Vixlet/docker-node
    tags: true
