language: node_js

node_js:
  - '0.12'

sudo: required

group: edge

services:
  - docker

env:
  - DOCKER_IMG_VERSION=v4_node_0.10.41
  - DOCKER_IMG_VERSION=v4_node_0.12.9
  - DOCKER_IMG_VERSION=v4_node_4.2.4
  - DOCKER_IMG_VERSION=v4_node_5.3.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.5.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - ./build.sh all --latest=v4_node_0.10.41 $DOCKER_IMG_VERSION

deploy:
  provider: script
  script: ./build.sh push --latest=v4_node_0.10.41 $DOCKER_IMG_VERSION
  on:
    tags: true