language: node_js

sudo: required

group: edge

services:
  - docker

matrix:
  include:
    - node_js: "4.5"
      env: NODE_VERSION_X=4
      services:
        - docker
    - node_js: "5.12"
      env: NODE_VERSION_X=5
      services:
        - docker
    - node_js: "6.5"
      env: NODE_VERSION_X=6
      services:
        - docker

before_install:
  - npm -g install npm@latest-2
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - ./tools/pre_push.sh

deploy:
  provider: script
  script: ./tools/push.sh
  on:
    repo: Vixlet/docker-node
    tags: true
